/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import controller.MyConnection;
import controller.inventoryBalanceDb;
import controller.itemDb;
import controller.purchaseDb;
import controller.salesDb;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author samrit
 */
public class Sales extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sales
     */
    String salesId;
    String sdate;
    String customerName;
    int itemid;
    String itemName;
    String iUnit;
    float quantity;
    float price;
    float total;
    double vat;
    double totalAmount;
    String transId;
    salesDb salDb = new salesDb(); 
    float v = 0.15f;
    Connection con;
    PreparedStatement ps ;
    ResultSet rs;
    float subtot;
    purchaseDb purDb = new purchaseDb();    
    itemDb itemDb = new itemDb();
    float updatQty =0;
    
    inventoryBalanceDb invDb = new inventoryBalanceDb();
    
   DefaultTableModel model;
    
    public Sales() {
        initComponents();
        salDb.autoId();
        
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)screensize.getWidth();
        int height = (int)screensize.getHeight();
        setSize(width-180, height-40);
        
        try {
            salDb.FillComboFullNames();
        } catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        salId = new javax.swing.JTextField();
        cusName = new javax.swing.JTextField();
        salDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        itemId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        salQty = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        salPrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        salTotal = new javax.swing.JTextField();
        salView = new javax.swing.JButton();
        salDelet = new javax.swing.JButton();
        cmbItemName = new javax.swing.JComboBox<>();
        iunt = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        transal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        salVat = new javax.swing.JLabel();
        saltotalamount = new javax.swing.JLabel();
        salSubtotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salSave = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1170, 670));

        jPanel1.setBackground(new java.awt.Color(0, 138, 207));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 670));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel8.setText("Sales Id");

        jLabel9.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel9.setText("Date");

        jLabel10.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel10.setText("Customer Name");

        salId.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N

        cusName.setColumns(2);
        cusName.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        cusName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusNameKeyTyped(evt);
            }
        });

        salDate.setMinSelectableDate(new java.util.Date(-62135776718000L));

        jLabel11.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel11.setText("Item Id");

        jLabel12.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel12.setText("Item Name");

        jLabel13.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel13.setText("Unit");

        itemId.setEditable(false);
        itemId.setColumns(11);
        itemId.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel14.setText("Quantity");

        salQty.setColumns(3);
        salQty.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        salQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salQtyKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel15.setText("Price");

        salPrice.setColumns(4);
        salPrice.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        salPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salPriceActionPerformed(evt);
            }
        });
        salPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salPriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salPriceKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel16.setText("Total");

        salTotal.setEditable(false);
        salTotal.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        salTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salTotalActionPerformed(evt);
            }
        });

        salView.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        salView.setText("Add");
        salView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salViewActionPerformed(evt);
            }
        });

        salDelet.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        salDelet.setText("Delete");
        salDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salDeletActionPerformed(evt);
            }
        });

        cmbItemName.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        cmbItemName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item Name" }));
        cmbItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemNameActionPerformed(evt);
            }
        });
        cmbItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbItemNameKeyPressed(evt);
            }
        });

        iunt.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        iunt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Unit", "PCS", "KG", "SET", "PACKAGE" }));

        jLabel17.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel17.setText("Transaction Id");

        transal.setEditable(false);
        transal.setColumns(10);
        transal.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cusName)
                    .addComponent(salDate, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(salId))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iunt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(transal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(salQty, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(itemId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salView, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel8, jLabel9});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel17});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(itemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(salTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(salView, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(salDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(transal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(iunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(salId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(salDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(salQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(salPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(69, Short.MAX_VALUE))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbItemName, cusName, itemId, iunt, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel8, jLabel9, salId, salPrice, salQty, salTotal});

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(472, 339));

        salTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TransactionId", "SalesId", "Date", "Customer Name", "Item Id", "Item Name", "Unit", "Quantity", "Price", "Total"
            }
        ));
        salTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                salTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        salTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salTable);

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total Amount");

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Vat");

        salVat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salVat.setForeground(new java.awt.Color(0, 102, 51));
        salVat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        salVat.setText("0.00");
        salVat.setToolTipText("");

        saltotalamount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saltotalamount.setForeground(new java.awt.Color(0, 102, 51));
        saltotalamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        saltotalamount.setText("0.00");

        salSubtotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salSubtotal.setForeground(new java.awt.Color(0, 102, 51));
        salSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        salSubtotal.setText("0.00");
        salSubtotal.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("SubTotal");

        salSave.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        salSave.setText("Save");
        salSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(589, Short.MAX_VALUE)
                .addComponent(salSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saltotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salVat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, salSubtotal, salVat, saltotalamount});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salSubtotal))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salVat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saltotalamount)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(salSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, salSubtotal, salVat, saltotalamount});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public boolean verifText(){
            if( salId.getText().equals("")|| salDate.getDate()==null ||itemId.getText().equals("")||cusName.getText().isEmpty()
                    ||itemId.getText().isEmpty() || salTotal.getText().isEmpty()
                 || cmbItemName.getSelectedIndex()==0  || iunt.getSelectedIndex()==0 || salQty.getText().equals(""))
                 
            {                  
                JOptionPane.showMessageDialog(null, "One or More Empty Field");

                
                 return false; 
        
            }
          
            
         return true;
     
    }     
    
    private void salSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salSaveActionPerformed
    
        if (salTable.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "There is Nothing to Save ");
        }else{
      
        int tm = salTable.getRowCount();
        
        for(int i= 0; i < tm; i++){
            
            transId = (String)salTable.getValueAt(i,0);
            salesId = (String)salTable.getValueAt(i,1);
            sdate = (String)salTable.getValueAt(i,2);
            customerName = (String)salTable.getValueAt(i,3);
            itemid = (int) salTable.getValueAt(i,4);
            quantity = (float)salTable.getValueAt(i,7);
            price = (float)salTable.getValueAt(i,8);
            total = (float)salTable.getValueAt(i,9);
            
        
        salDb.insertSalesItem(transId, salesId, sdate, customerName, itemid, quantity, price, total);
        invDb.insertPurInventory(transId, sdate, itemid, 0 , quantity);
                
        subtot = Float.parseFloat(salSubtotal.getText());
        totalAmount = Float.parseFloat(saltotalamount.getText());
        vat = Float.parseFloat(salVat.getText());
        float currentqty = itemDb.getendQty(itemid);
        updatQty = currentqty - quantity;
        itemDb.updateqty(itemid, updatQty);
             }
        salDb.insert(salesId, sdate,  subtot,  vat, totalAmount);
        JOptionPane.showMessageDialog(rootPane, "Successfully Inserted");
        
      

        while (model.getRowCount() >0){
            for(int i =0; i < model.getRowCount(); i++){
                model.removeRow(i);
            }
            salId.setText("");
            salDate.setDate(new Date());
            cusName.setText("");
            salSubtotal.setText("0.00");
            salVat.setText("0.00");
            saltotalamount.setText("0.00");
            salDb.autoId();
        }
 }
        
    }//GEN-LAST:event_salSaveActionPerformed

    private void salTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salTotalActionPerformed

    private void salViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salViewActionPerformed
    
        if(verifText()){
            
        transId = transal.getText();
        salesId =  salId.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        sdate = dateFormat.format(salDate.getDate());
        customerName = cusName.getText();
        itemid =  Integer.parseInt(itemId.getText());
        itemName = cmbItemName.getSelectedItem().toString();
        iUnit = iunt.getSelectedItem().toString();
        quantity = Float.parseFloat(salQty.getText());
        price = Float.parseFloat(salPrice.getText());
        total = Float.parseFloat(salTotal.getText());
        vat= Float.parseFloat(salVat.getText());
        totalAmount= Float.parseFloat(saltotalamount.getText());
        subtot = Float.parseFloat(salSubtotal.getText());
        
       if(!salDb.isSalesExist(salesId) && !salDb.isTransactionExist(transId)){
            try {
               itemid = Integer.parseInt(itemId.getText());
                con = MyConnection.getConnection();

                ps  = con.prepareStatement( "select * from stockreportdetail where itemId=?");

                ps.setInt(1,itemid);
                rs= ps.executeQuery();

                while(rs.next()){ 
                    float currentqty;
                    currentqty = rs.getFloat("Balance");
                   // float qtyNew = Float.parseFloat(salQty.getText());
                    if(quantity > currentqty){
                        JOptionPane.showMessageDialog(this, "Available Qty is "+" = " +currentqty +" Only");
                    }

                else{
                     
                       model =  (DefaultTableModel) salTable.getModel();
                       model.addRow(new Object[]
                       {
                           transId,
                            salesId,
                            sdate,
                            customerName,
                            itemid,
                            itemName,
                            iUnit,
                            quantity,
                            price,
                            total,
                          
                       });
                        double sum=0.00;
                        vat =0.00;
                        double tot=0.00;
                        for(int i=0; i < salTable.getRowCount(); i++){
                            
                         sum = sum + Double.parseDouble(salTable.getValueAt(i, 9).toString());
                        
                         vat = sum * v;
                       
                         tot = vat +sum;
   
            }
                        
        DecimalFormat df=new DecimalFormat("0.00");
        salSubtotal.setText(df.format(sum));
        salVat.setText(df.format(vat));
        saltotalamount.setText(df.format(tot));
                            
            String rnno = transal.getText();
            int co = rnno.length();
            String txt = rnno.substring(0,3);
            String num = rnno.substring(3,co);
            int n = Integer.parseInt(num);
            n++;
            String snum = Integer.toString(n);
            String ftxt = txt +snum;
            transal.setText(ftxt);
                
            itemId.setText("");
            cmbItemName.setSelectedIndex(0);
            iunt.setSelectedIndex(0);
            salQty.setText("");
            salPrice.setText("");
            salTotal.setText("");            
                }
            }
       
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
         
        }
         }else{
           JOptionPane.showMessageDialog(this, "Sales Id already exist!");
       }
        
                           
}
                                     

        
    }//GEN-LAST:event_salViewActionPerformed

    private void cmbItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbItemNameKeyPressed

    }//GEN-LAST:event_cmbItemNameKeyPressed

    private void cmbItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemNameActionPerformed
        try {
            salDb.CompoItemName();
        } catch (SQLException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbItemNameActionPerformed

    private void salPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salPriceKeyReleased
        if (salPrice.getText().isEmpty()){
            salPrice.setText("0");
        }
        if ((!salQty.getText().isEmpty())){
            quantity = Float.parseFloat(salQty.getText());
            price = Float.parseFloat(salPrice.getText());
            
            float tot = quantity * price;
            
            String tot1 =Float.toString(tot);
         
            salTotal.setText(tot1);
        
        }else{
            salTotal.setText("0");

        }
    }//GEN-LAST:event_salPriceKeyReleased

    private void salTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salTableMouseClicked

    }//GEN-LAST:event_salTableMouseClicked

    private void salDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salDeletActionPerformed
//         salesId =  salId.getText();
//         salDb.delete(salesId);
             model =  (DefaultTableModel) salTable.getModel();
            int i = salTable.getSelectedRow();
            if(i>=0){
                model.removeRow(i);
                 salSubtotal.setText("0.00");
                 salVat.setText("0.00");
                 saltotalamount.setText("0.00");

            }else
            {
                JOptionPane.showMessageDialog(this, "Unable to Delete");
}

    }//GEN-LAST:event_salDeletActionPerformed

    private void salQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salQtyKeyTyped
              
        char c = evt.getKeyChar();
        if(Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
    }                     
                   
    }//GEN-LAST:event_salQtyKeyTyped

    private void salTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_salTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_salTableAncestorAdded

    private void salPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salPriceKeyTyped
              
        char c = evt.getKeyChar();
        if(Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
    }                     
    }//GEN-LAST:event_salPriceKeyTyped

    private void cusNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusNameKeyTyped
         if(cusName.getText().length() >= 30){
            evt.consume();
        }
    }//GEN-LAST:event_cusNameKeyTyped

    private void salPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmbItemName;
    public static javax.swing.JTextField cusName;
    public static javax.swing.JTextField itemId;
    public static javax.swing.JComboBox<String> iunt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static com.toedter.calendar.JDateChooser salDate;
    private javax.swing.JButton salDelet;
    public static javax.swing.JTextField salId;
    public static javax.swing.JTextField salPrice;
    public static javax.swing.JTextField salQty;
    private javax.swing.JButton salSave;
    private javax.swing.JLabel salSubtotal;
    public static javax.swing.JTable salTable;
    public static javax.swing.JTextField salTotal;
    private javax.swing.JLabel salVat;
    private javax.swing.JButton salView;
    private javax.swing.JLabel saltotalamount;
    public static javax.swing.JTextField transal;
    // End of variables declaration//GEN-END:variables
}
